# Generated by Django 3.1.7 on 2023-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_orderupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=250, null=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=''),
        ),
    ]
