# Generated by Django 3.0.5 on 2023-07-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='phone',
        ),
    ]
