# Generated by Django 3.0.5 on 2023-07-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20230703_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='Email',
        ),
    ]
